name: Build and Deploy pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        working-directory: OpenApi
        run: npx @redocly/cli bundle openapi.yaml -o dist/PlagiarismCheckerApi/openapi.yaml

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: OpenAPI/dist
          branch: gh-pages