name: Build and Deploy pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - OpenApi/openapi.yaml
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        working-directory: OpenApi
        run: npx @redocly/cli bundle openapi.yaml -o docs/openapi.yaml

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: OpenApi/docs